# -*- coding: utf-8 -*-
"""ADMEP_Assignment_1.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyD562uJ75vXXpcfBkj4jEvPIqIIYMZ8
"""

# Goal: Analyze the dataset to help a retail company improve marketing strategies by targeting specific customer segments.
# Dataset: Customer transactions with fields like Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount.

import pandas as pd
df = pd.read_csv("retail_sales_dataset.csv")
print("Here are the first 5 transactions in the dataset:")
print(df.head(5))

print("\nChecking for missing values in the dataset:")
print(df.isnull().sum())

# Explanation:
# We load the dataset using pandas.
# Checking the first 5 rows helps understand the structure.
# Missing value check ensures data is clean.

#Step 2: Customer Segmentation by Age

df['Age Group'] = pd.cut(df['Age'], bins=[0, 25, 40, 60, 100],
                         labels=["18-25", "26-40", "41-60", "60+"])

spending_by_age_group = df.groupby('Age Group')['Total Amount'].sum()

print("\nTotal spending per age group:")
print(spending_by_age_group)

# Explanation:
# Age groups help identify which age segments spend more.
# Grouping and summing Total Amount shows the high-value age groups.

#Step 3: Total spending per gender

spending_by_gender = df.groupby('Gender')['Total Amount'].sum()
print("\nTotal spending per gender:")
print(spending_by_gender)


# Explanation:
# Understanding spending by gender helps design gender-targeted campaigns.

# Step 4: Popular Product Categories
# Count purchases by category
popular_category = df['Product Category'].value_counts()
print("\nMost popular product categories:")
print(popular_category)

# Total revenue per category
revenue_by_category = df.groupby('Product Category')['Total Amount'].sum()
print("\nTotal revenue per product category:")
print(revenue_by_category)


# Explanation:
# value_counts() shows which products are bought most often.
# Revenue per category identifies profitable categories to target promotions.

# Step 5: High-Value Customers
# Define high-value customers: total spending > 1000
customer_spending = df.groupby('Customer ID')['Total Amount'].sum()
high_value_customers = customer_spending[customer_spending > 1000]

print("\nHigh-value customers (Total spending > 1000):")
print(high_value_customers)


# Explanation:
# High-value customers can be offered loyalty programs, exclusive discounts, or VIP campaigns.

import matplotlib.pyplot as plt
import seaborn as sns

# Create a 2x2 subplot figure
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# Plot spending by age group
sns.barplot(x=spending_by_age_group.index, y=spending_by_age_group.values, palette='coolwarm', ax=axes[0,0])
axes[0,0].set_title("Total Spending by Age Group")
axes[0,0].set_xlabel("Age Group")
axes[0,0].set_ylabel("Total Amount")

# Plot spending by gender
sns.barplot(x=spending_by_gender.index, y=spending_by_gender.values, palette='pastel', ax=axes[0,1])
axes[0,1].set_title("Total Spending by Gender")
axes[0,1].set_xlabel("Gender")
axes[0,1].set_ylabel("Total Amount")

# Plot product category popularity
sns.barplot(x=popular_category.index, y=popular_category.values, palette='viridis', ax=axes[1,0])
axes[1,0].set_title("Most Popular Product Categories")
axes[1,0].set_xlabel("Product Category")
axes[1,0].set_ylabel("Number of Purchases")
axes[1,0].tick_params(axis='x', rotation=45)

# Plot revenue by product category
sns.barplot(x=revenue_by_category.index, y=revenue_by_category.values, palette='magma', ax=axes[1,1])
axes[1,1].set_title("Revenue by Product Category")
axes[1,1].set_xlabel("Product Category")
axes[1,1].set_ylabel("Total Revenue")
axes[1,1].tick_params(axis='x', rotation=45)

# Adjust layout
plt.tight_layout()
plt.show()

# Recommendations
print("\n--- Marketing Recommendations ---")
print("1. Age-based targeting: 18-25 (social media), 26-40 (emails/bundles), 41-60 (personalized promotions), 60+ (special offers)")
print("2. Gender-based campaigns: Females (beauty/clothing), Males (electronics/gadgets)")
print("3. Product category focus: Clothing (frequent buyers), Electronics (highest revenue)")
print("4. High-value customers: Loyalty programs, exclusive deals, VIP engagement")

